/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Digital_MHC (https://sketchfab.com/Digital_MHC)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nicola-sofa-44ed972d6f5a400abe0b2144b46d4496
Title: Nicola Sofa
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Model(props) {
  const { nodes, materials } = useGLTF("/images/sofa/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.sofa_MHC}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.sofa_MHC}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.sofa_MHC}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.sofa_MHC}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.nikel_legs}
        />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Pillows} />
      </group>
    </group>
  );
}

useGLTF.preload("sofa/scene.gltf");
export default Model;
